badge:
    resource: "@BadgeBundle/Resources/config/routing.yml"
    prefix:   "/badge"

news:
    resource: "@NewsBundle/Resources/config/routing.yml"
    prefix:   "/"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
