news_list:
    path:     "/news"
    defaults: { _controller: NewsBundle:News:index }
news_show:
    pattern:  "/news/{id}"
    defaults: { _controller: NewsBundle:News:show }
    requirements:
        id: '\d+'
news_create:
    pattern:  "/news/create"
    defaults: { _controller: NewsBundle:News:create }

news_remove:
    pattern:  "/news/remove/{id}"
    defaults: { _controller: NewsBundle:News:remove }
    requirements:
        id: '\d+'
