services:
    newsbundle.eventlistener.postremovelogger:
        class: NewsBundle\Listener\PostRemoveLogger
        arguments:
            - "@logger"
        tags:
            - name: doctrine.event_listener
              event: postRemove
            - name: monolog.logger
              channel: news
